name: build and push image

inputs:
  image: 
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:    
  - name: Build and Push Image
    run: |
      # docker buildx create --use --config /etc/buildkitd.toml
      # docker buildx inspect --bootstrap
      docker buildx build . -t registry.container-registry:5000/${IMAGE}:${SHA} --push
    env:
      IMAGE: ${{inputs.image}}
      SHA: ${{github.sha}}
    shell: bash
