name: deploy

inputs:
  tag: 
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
  - name: Build and Push Image
    run: build ${{ inputs.tag }}
    shell: bash
  - name: Deploy
    uses: s0/git-publish-subdir-action@develop
    env:
      REPO: self
      BRANCH: manifest # The branch name where you want to push the assets
      FOLDER: .argo # The directory where your assets are generated
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
      MESSAGE: "Build: ({sha}) {msg}" # The commit message
