name: Reusable workflow example

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  echo:
    runs-on: self-hosted
    steps:
    - name: echo
      uses: quartzsoftwarellc/.github/actions/echo@main
      with:
        message: ${{ inputs.message }}

