name: Reusable workflow example

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  triage:
    runs-on: self-hosted
    steps:
    - name: echo
      uses: ./.github/actions/echo
      with:
        messae: ${{ inputs.message }}

