# .github/workflows/publish.yml
name: Build Pkgdown Site Image and Push to Docker Repository

on:
  workflow_call:
    inputs:
      subdomain:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    name: Build and Push
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          Rscript -e 'devtools::build_site()'
      - name: Prepare Docker and Kustomize
        env:
          SUBDOMAIN: ${{ inputs.subdomain }}
        run: |
          # add docker file
          tee Dockerfile <<EOF

          FROM nginx:alpine
          COPY docs /usr/share/nginx/html

          EOF

      - uses: quartzsoftwarellc/.github/actions/deploy@main
        with:
          image: ${{inputs.subdomain}}-docs