# .github/workflows/publish.yml
name: Build Pkgdown Site Image and Push to Docker Repository

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: self-hosted
    name: Build and Push
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          Rscript -e 'devtools::build_site()'
      - uses: quartzsoftwarellc/.github/actions/deploy@main
        with:
          image: rscrapers-docs
          github_token: ${{ secrets.GITHUB_TOKEN }}