name: Run Test R

on:
  workflow_call:

jobs:
  Scrape:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          Rscript -e "devtools::test()"

