name: Run Test R

on:
  workflow_call:
    inputs:
      integration:
        required: false
        default: "FALSE"
        type: string


jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: quartzsoftwarellc/.github/actions/test-r@main
        env:
          INTEGRATION: ${{ inputs.integration }}


